# Generated by Django 3.0.5 on 2021-04-20 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='app',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game_id', models.IntegerField()),
                ('game_name', models.CharField(max_length=200)),
                ('game_category', models.CharField(max_length=200)),
                ('game_players', models.IntegerField()),
                ('game_downloads', models.IntegerField()),
            ],
        ),
    ]
